#!/usr/bin/env bash
# Generate ~/.litellm/config.yaml by detecting running inference services
# and prompting for cloud API keys
set -e

CONFIG_DIR="$HOME/.litellm"
CONFIG_FILE="$CONFIG_DIR/config.yaml"
ENV_FILE="$CONFIG_DIR/.env"

mkdir -p "$CONFIG_DIR"

echo "========================================"
echo " LiteLLM Config Generator"
echo "========================================"
echo ""

# --- Detect running services ---
OLLAMA_RUNNING=false
VLLM_RUNNING=false
VLLM_MODEL=""

if curl -sf http://localhost:11434/api/version >/dev/null 2>&1; then
    OLLAMA_RUNNING=true
fi

if docker ps --format '{{.Names}}' 2>/dev/null | grep -q "^vllm$"; then
    VLLM_RUNNING=true
    VLLM_MODEL=$(docker inspect vllm --format '{{join .Args " "}}' 2>/dev/null | grep -oP '(?<=--model )\S+' || echo "")
fi

# --- Detect Ollama models ---
OLLAMA_MODELS=()
if $OLLAMA_RUNNING; then
    echo "Ollama detected on :11434"
    while IFS= read -r model; do
        [ -n "$model" ] && OLLAMA_MODELS+=("$model")
    done < <(curl -sf http://localhost:11434/api/tags 2>/dev/null | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    for m in data.get('models', []):
        print(m['name'])
except: pass
" 2>/dev/null)

    if [ ${#OLLAMA_MODELS[@]} -gt 0 ]; then
        echo "  Models: ${OLLAMA_MODELS[*]}"
    else
        echo "  No models pulled yet. Pull some with: ollama pull <model>"
    fi
else
    echo "Ollama not detected (start with: systemctl start ollama)"
fi

echo ""

if $VLLM_RUNNING; then
    echo "vLLM detected on :8020"
    [ -n "$VLLM_MODEL" ] && echo "  Model: $VLLM_MODEL"
else
    echo "vLLM not running (start with: vllm <model_name>)"
fi

echo ""

# --- Cloud API keys ---
echo "Cloud API keys (leave blank to skip):"
echo ""

OPENAI_KEY=""
ANTHROPIC_KEY=""
GEMINI_KEY=""

read -rp "  OpenAI API key: " OPENAI_KEY
read -rp "  Anthropic API key: " ANTHROPIC_KEY
read -rp "  Google Gemini API key: " GEMINI_KEY

echo ""

# --- Write env file ---
if [ -n "$OPENAI_KEY" ] || [ -n "$ANTHROPIC_KEY" ] || [ -n "$GEMINI_KEY" ]; then
    cat > "$ENV_FILE" << EOF
${OPENAI_KEY:+OPENAI_API_KEY=$OPENAI_KEY}
${ANTHROPIC_KEY:+ANTHROPIC_API_KEY=$ANTHROPIC_KEY}
${GEMINI_KEY:+GEMINI_API_KEY=$GEMINI_KEY}
EOF
    # Remove blank lines
    sed -i '/^$/d' "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    echo "Saved API keys to $ENV_FILE"
else
    # Create empty env file so docker --env-file doesn't fail
    touch "$ENV_FILE"
fi

# --- Generate config ---
cat > "$CONFIG_FILE" << 'HEADER'
# LiteLLM Proxy Configuration
# Generated by setup-litellm-config.sh
# Regenerate anytime with: ~/dgx-toolbox/setup-litellm-config.sh

model_list:
HEADER

# Add Ollama models
if $OLLAMA_RUNNING && [ ${#OLLAMA_MODELS[@]} -gt 0 ]; then
    echo "  # --- Ollama models (localhost:11434) ---" >> "$CONFIG_FILE"
    for model in "${OLLAMA_MODELS[@]}"; do
        # Strip :latest suffix for the model_name
        name="${model%%:latest}"
        cat >> "$CONFIG_FILE" << EOF
  - model_name: ${name}
    litellm_params:
      model: ollama/${model}
      api_base: http://host.docker.internal:11434
EOF
    done
    echo "" >> "$CONFIG_FILE"
fi

# Add vLLM model
if $VLLM_RUNNING && [ -n "$VLLM_MODEL" ]; then
    cat >> "$CONFIG_FILE" << EOF
  # --- vLLM model (localhost:8020) ---
  - model_name: ${VLLM_MODEL}
    litellm_params:
      model: openai/${VLLM_MODEL}
      api_base: http://host.docker.internal:8020/v1
      api_key: "none"

EOF
fi

# Add cloud models
if [ -n "$OPENAI_KEY" ]; then
    cat >> "$CONFIG_FILE" << 'EOF'
  # --- OpenAI models ---
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini

EOF
fi

if [ -n "$ANTHROPIC_KEY" ]; then
    cat >> "$CONFIG_FILE" << 'EOF'
  # --- Anthropic models ---
  - model_name: claude-sonnet
    litellm_params:
      model: anthropic/claude-sonnet-4-20250514
  - model_name: claude-haiku
    litellm_params:
      model: anthropic/claude-haiku-4-5-20251001

EOF
fi

if [ -n "$GEMINI_KEY" ]; then
    cat >> "$CONFIG_FILE" << 'EOF'
  # --- Google Gemini models ---
  - model_name: gemini-2.5-pro
    litellm_params:
      model: gemini/gemini-2.5-pro-preview-06-05
  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash-preview-05-20
  - model_name: gemini-2.0-flash
    litellm_params:
      model: gemini/gemini-2.0-flash

EOF
fi

# Add commented-out templates for services not yet running
if ! $OLLAMA_RUNNING || [ ${#OLLAMA_MODELS[@]} -eq 0 ]; then
    cat >> "$CONFIG_FILE" << 'EOF'
  # --- Ollama models (uncomment after pulling models) ---
  # - model_name: llama3.1
  #   litellm_params:
  #     model: ollama/llama3.1
  #     api_base: http://host.docker.internal:11434

EOF
fi

if ! $VLLM_RUNNING; then
    cat >> "$CONFIG_FILE" << 'EOF'
  # --- vLLM model (uncomment when running) ---
  # - model_name: nvidia/Llama-3.1-Nemotron-Nano-8B-v1
  #   litellm_params:
  #     model: openai/nvidia/Llama-3.1-Nemotron-Nano-8B-v1
  #     api_base: http://host.docker.internal:8020/v1
  #     api_key: "none"

EOF
fi

if [ -z "$OPENAI_KEY" ]; then
    cat >> "$CONFIG_FILE" << 'EOF'
  # --- OpenAI (set OPENAI_API_KEY in ~/.litellm/.env) ---
  # - model_name: gpt-4o
  #   litellm_params:
  #     model: openai/gpt-4o

EOF
fi

if [ -z "$ANTHROPIC_KEY" ]; then
    cat >> "$CONFIG_FILE" << 'EOF'
  # --- Anthropic (set ANTHROPIC_API_KEY in ~/.litellm/.env) ---
  # - model_name: claude-sonnet
  #   litellm_params:
  #     model: anthropic/claude-sonnet-4-20250514

EOF
fi

if [ -z "$GEMINI_KEY" ]; then
    cat >> "$CONFIG_FILE" << 'EOF'
  # --- Google Gemini (set GEMINI_API_KEY in ~/.litellm/.env) ---
  # - model_name: gemini-2.5-pro
  #   litellm_params:
  #     model: gemini/gemini-2.5-pro-preview-06-05

EOF
fi

# Settings
cat >> "$CONFIG_FILE" << 'EOF'
litellm_settings:
  drop_params: true
  set_verbose: false
EOF

echo ""
echo "Config written to $CONFIG_FILE"
echo ""
echo "To apply: litellm-stop && litellm"
echo "To regenerate: ~/dgx-toolbox/setup-litellm-config.sh"
